# Generated by Django 5.1.2 on 2024-10-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0002_alter_product_updated_at_order_orderitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
