# Generated by Django 5.1.2 on 2024-11-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0004_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
