name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linting (flake8)
      run: |
        pip install flake8
        flake8 .

    - name: Run tests with pytest
      run: |
        pip install pytest
        pytest --maxfail=1 --disable-warnings -q

    - name: Build Docker containers
      run: |
        docker-compose -f docker-compose.yml build
