name: Django E-Commerce CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 3: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Set up PostgreSQL for testing (optional if you are running DB tests)
    - name: Set up PostgreSQL
      uses: docker://postgres:latest
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: ecommerce_db
      with:
        name: postgres
        ports: 5432:5432

    # Step 5: Run migrations (if your tests require DB setup)
    - name: Run migrations
      run: |
        python manage.py migrate

    # Step 6: Run tests with pytest (adjust according to your testing framework)
    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q

    # Optional: Add additional steps for linting or deployment
    - name: Lint code (Optional)
      run: |
        pip install flake8
        flake8 .

    # Optional: Deploy your app (you can customize this based on your deployment method)
    - name: Deploy to server (Optional)
      run: |
        # Add your deployment script here (e.g., deploy to Heroku, AWS, etc.)
        echo "Deploying to server..."
